#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Apr 13 00:13:14 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import wx.richtext
# end wxGlade


class AppWindowBase(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AppWindowBase.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("WhaddaDoo")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.window_1 = wx.SplitterWindow(self.panel_1, wx.ID_ANY)
        self.window_1.SetMinimumPaneSize(20)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)

        self.window_1_pane_1 = wx.Panel(self.window_1, wx.ID_ANY)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.rtc_tasks = wx.richtext.RichTextCtrl(self.window_1_pane_1, wx.ID_ANY, style=wx.VSCROLL|wx.HSCROLL|wx.NO_BORDER)
        sizer_2.Add(self.rtc_tasks, 1, wx.EXPAND, 0)

        self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        sizer_3.Add((0, 0), 0, 0, 0)

        self.window_1_pane_2.SetSizer(sizer_3)

        self.window_1_pane_1.SetSizer(sizer_2)

        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()

        self.Bind(wx.EVT_SHOW, self.on_frame_show, self)
        # end wxGlade

    def on_frame_show(self, event):  # wxGlade: AppWindowBase.<event_handler>
        print("Event handler 'on_frame_show' not implemented!")
        event.Skip()

# end of class AppWindowBase

class MyApp(wx.App):
    def OnInit(self):
        self.frame = AppWindowBase(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
